%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/AreVa/PycharmProjects/TestPandas/tick.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/18 12:21:53

%% Initialize variables.
filename = '/Users/AreVa/PycharmProjects/TestPandas/tick.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%*q%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Price = dataArray{:, 1};
VolBuy = dataArray{:, 2};
VolSell = dataArray{:, 3};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/AreVa/PycharmProjects/TestPandas/tick.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/09/18 12:22:27

%% Initialize variables.
filename = '/Users/AreVa/PycharmProjects/TestPandas/tick.csv';
delimiter = ',';

%% Format string for each line of text:
%   column2: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*q%q%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
x = [dataArray{1:end-1}];
DateTime = datetime(x, 'InputFormat', 'yyyy-MM-dd HH:mm:ss');
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans x;